# Generated by Django 5.1.15 on 2026-02-24 04:58

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=300)),
                ('units_count', models.PositiveIntegerField(default=0, help_text='Planned number of units')),
                ('common_areas', models.TextField(blank=True, default='')),
                ('maintenance_fee', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('currency', models.CharField(choices=[('MXN', 'Peso Mexicano'), ('USD', 'US Dollar'), ('EUR', 'Euro'), ('COP', 'Peso Colombiano')], default='MXN', max_length=3)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='tenant_logos/')),
                ('operation_start_date', models.CharField(default='2024-01', help_text='Format: YYYY-MM', max_length=7)),
                ('operation_type', models.CharField(choices=[('fiscal', 'Año Fiscal (Ene-Dic)'), ('custom', 'Personalizado')], default='fiscal', max_length=10)),
                ('country', models.CharField(blank=True, default='', max_length=100)),
                ('state', models.CharField(blank=True, default='', max_length=100)),
                ('bank_initial_balance', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('admin_type', models.CharField(choices=[('mesa_directiva', 'Mesa Directiva'), ('administrador', 'Administrador Externo'), ('comite', 'Comité')], default='mesa_directiva', max_length=20)),
                ('razon_social', models.CharField(blank=True, default='', max_length=300)),
                ('rfc', models.CharField(blank=True, default='', max_length=20)),
                ('info_calle', models.CharField(blank=True, default='', max_length=300)),
                ('info_num_externo', models.CharField(blank=True, default='', max_length=50)),
                ('info_colonia', models.CharField(blank=True, default='', max_length=200)),
                ('info_delegacion', models.CharField(blank=True, default='', max_length=200)),
                ('info_ciudad', models.CharField(blank=True, default='', max_length=200)),
                ('info_codigo_postal', models.CharField(blank=True, default='', max_length=10)),
                ('addr_nombre', models.CharField(blank=True, default='', max_length=300)),
                ('addr_calle', models.CharField(blank=True, default='', max_length=300)),
                ('addr_num_externo', models.CharField(blank=True, default='', max_length=50)),
                ('addr_colonia', models.CharField(blank=True, default='', max_length=200)),
                ('addr_delegacion', models.CharField(blank=True, default='', max_length=200)),
                ('addr_ciudad', models.CharField(blank=True, default='', max_length=200)),
                ('addr_codigo_postal', models.CharField(blank=True, default='', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'tenants',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_super_admin', models.BooleanField(default=False)),
                ('must_change_password', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'users',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ReopenRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('period', models.CharField(max_length=7)),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('approved', 'Aprobado'), ('rejected', 'Rechazado')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reopen_requests', to=settings.AUTH_USER_MODEL)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_reopen_requests', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reopen_requests', to='core.tenant')),
            ],
            options={
                'db_table': 'reopen_requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExtraField',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=200)),
                ('default_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('required', models.BooleanField(default=False)),
                ('enabled', models.BooleanField(default=True)),
                ('cross_unit', models.BooleanField(default=False, help_text='Can target another unit')),
                ('field_type', models.CharField(choices=[('normal', 'Normal'), ('gastos', 'Gastos')], default='normal', max_length=10)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_system_default', models.BooleanField(default=False, help_text='Created by system, cannot delete')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extra_fields', to='core.tenant')),
            ],
            options={
                'db_table': 'extra_fields',
                'ordering': ['sort_order', 'label'],
            },
        ),
        migrations.CreateModel(
            name='Committee',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('members', models.TextField(blank=True, default='', help_text='Comma-separated member names')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='committees', to='core.tenant')),
            ],
            options={
                'db_table': 'committees',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('unit_name', models.CharField(help_text='e.g. Casa 1, Depto 301', max_length=100)),
                ('unit_id_code', models.CharField(db_index=True, help_text='e.g. C-001, D-301', max_length=50)),
                ('owner_first_name', models.CharField(blank=True, default='', max_length=150)),
                ('owner_last_name', models.CharField(blank=True, default='', max_length=150)),
                ('owner_email', models.EmailField(blank=True, default='', max_length=254)),
                ('owner_phone', models.CharField(blank=True, default='', max_length=30)),
                ('occupancy', models.CharField(choices=[('propietario', 'Propietario'), ('rentado', 'Rentado'), ('vacío', 'Vacío')], default='propietario', max_length=15)),
                ('tenant_first_name', models.CharField(blank=True, default='', help_text='Renter first name', max_length=150)),
                ('tenant_last_name', models.CharField(blank=True, default='', max_length=150)),
                ('tenant_email', models.EmailField(blank=True, default='', max_length=254)),
                ('tenant_phone', models.CharField(blank=True, default='', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='core.tenant')),
            ],
            options={
                'db_table': 'units',
                'ordering': ['unit_id_code'],
            },
        ),
        migrations.CreateModel(
            name='TenantUser',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('admin', 'Administrador'), ('tesorero', 'Tesorero'), ('contador', 'Contador'), ('auditor', 'Auditor'), ('vecino', 'Vecino / Residente')], db_index=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenant_users', to='core.tenant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenant_roles', to=settings.AUTH_USER_MODEL)),
                ('unit', models.ForeignKey(blank=True, help_text='Required for vecino role', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_users', to='core.unit')),
            ],
            options={
                'db_table': 'tenant_users',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('period', models.CharField(db_index=True, help_text='Format: YYYY-MM', max_length=7)),
                ('status', models.CharField(choices=[('pendiente', 'Pendiente'), ('parcial', 'Parcial'), ('pagado', 'Pagado')], default='pendiente', max_length=10)),
                ('payment_type', models.CharField(blank=True, choices=[('transferencia', 'Transferencia'), ('deposito', 'Depósito'), ('efectivo', 'Efectivo')], default='', max_length=15)),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('evidence', models.TextField(blank=True, default='', help_text='Base64 evidence image')),
                ('adeudo_payments', models.JSONField(blank=True, default=dict, help_text='Debt payments: {period: {fieldId: amount}}')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='core.tenant')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='core.unit')),
            ],
            options={
                'db_table': 'payments',
            },
        ),
        migrations.CreateModel(
            name='FieldPayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('field_key', models.CharField(help_text='"maintenance" or ExtraField.id', max_length=100)),
                ('received', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('adelanto_targets', models.JSONField(blank=True, default=dict)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_payments', to='core.payment')),
                ('target_unit', models.ForeignKey(blank=True, help_text='Cross-unit target', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.unit')),
            ],
            options={
                'db_table': 'field_payments',
            },
        ),
        migrations.CreateModel(
            name='AssemblyPosition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('holder_name', models.CharField(blank=True, default='', max_length=300)),
                ('active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assembly_positions', to='core.tenant')),
                ('holder_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.unit')),
            ],
            options={
                'db_table': 'assembly_positions',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='UnrecognizedIncome',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('period', models.CharField(max_length=7)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('description', models.CharField(blank=True, default='', max_length=500)),
                ('date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unrecognized_income', to='core.tenant')),
            ],
            options={
                'db_table': 'unrecognized_income',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GastoEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('period', models.CharField(db_index=True, max_length=7)),
                ('field_id_legacy', models.CharField(blank=True, default='', help_text='Legacy field ID for migration', max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('payment_type', models.CharField(choices=[('efectivo', 'Efectivo'), ('cheque', 'Cheque'), ('transferencia', 'Transferencia')], default='transferencia', max_length=15)),
                ('doc_number', models.CharField(blank=True, default='', max_length=100)),
                ('gasto_date', models.DateField(blank=True, null=True)),
                ('provider_name', models.CharField(blank=True, default='', max_length=300)),
                ('provider_rfc', models.CharField(blank=True, default='', max_length=20)),
                ('provider_invoice', models.CharField(blank=True, default='', max_length=100)),
                ('bank_reconciled', models.BooleanField(default=False)),
                ('evidence', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('field', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gasto_entries', to='core.extrafield')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gasto_entries', to='core.tenant')),
            ],
            options={
                'db_table': 'gasto_entries',
                'ordering': ['-gasto_date', '-created_at'],
                'indexes': [models.Index(fields=['tenant', 'period'], name='gasto_entri_tenant__34c91d_idx')],
            },
        ),
        migrations.CreateModel(
            name='ClosedPeriod',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('period', models.CharField(db_index=True, max_length=7)),
                ('closed_at', models.DateTimeField(auto_now_add=True)),
                ('closed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='closed_periods', to='core.tenant')),
            ],
            options={
                'db_table': 'closed_periods',
                'unique_together': {('tenant', 'period')},
            },
        ),
        migrations.CreateModel(
            name='CajaChicaEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('period', models.CharField(db_index=True, max_length=7)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('description', models.CharField(max_length=500)),
                ('date', models.DateField(blank=True, null=True)),
                ('payment_type', models.CharField(choices=[('efectivo', 'Efectivo'), ('cheque', 'Cheque'), ('transferencia', 'Transferencia')], default='efectivo', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='caja_chica_entries', to='core.tenant')),
            ],
            options={
                'db_table': 'caja_chica',
                'ordering': ['-date', '-created_at'],
                'indexes': [models.Index(fields=['tenant', 'period'], name='caja_chica_tenant__ab457e_idx')],
            },
        ),
        migrations.CreateModel(
            name='BankStatement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('period', models.CharField(max_length=7)),
                ('file_data', models.TextField(help_text='Base64 encoded PDF')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_statements', to='core.tenant')),
            ],
            options={
                'db_table': 'bank_statements',
                'unique_together': {('tenant', 'period')},
            },
        ),
        migrations.AddIndex(
            model_name='unit',
            index=models.Index(fields=['tenant', 'unit_name'], name='units_tenant__83475c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='unit',
            unique_together={('tenant', 'unit_id_code')},
        ),
        migrations.AddIndex(
            model_name='tenantuser',
            index=models.Index(fields=['tenant', 'role'], name='tenant_user_tenant__24f612_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='tenantuser',
            unique_together={('tenant', 'user')},
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['tenant', 'period'], name='payments_tenant__6f4e6b_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['tenant', 'period', 'status'], name='payments_tenant__ec0e50_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['unit', 'period'], name='payments_unit_id_f1d776_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='payment',
            unique_together={('tenant', 'unit', 'period')},
        ),
        migrations.AlterUniqueTogether(
            name='fieldpayment',
            unique_together={('payment', 'field_key')},
        ),
    ]
