# Generated by Django 5.1.15 on 2026-02-24 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='logo',
            field=models.TextField(blank=True, default='', help_text='Base64-encoded logo image'),
        ),
    ]
