# Generated by Django 5.1.15 on 2026-02-25 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_logo_base64'),
    ]

    operations = [
        migrations.AddField(
            model_name='committee',
            name='exemption',
            field=models.BooleanField(default=False),
        ),
    ]
