# Generated by Django 5.1.15 on 2026-02-25 06:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_add_committee_exemption'),
    ]

    operations = [
        migrations.AddField(
            model_name='assemblyposition',
            name='committee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='positions', to='core.committee'),
        ),
        migrations.AddField(
            model_name='assemblyposition',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='assemblyposition',
            name='end_date',
            field=models.CharField(blank=True, default='', help_text='YYYY-MM period', max_length=7),
        ),
        migrations.AddField(
            model_name='assemblyposition',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='assemblyposition',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='assemblyposition',
            name='start_date',
            field=models.CharField(blank=True, default='', help_text='YYYY-MM period', max_length=7),
        ),
    ]
