# Generated by Django 5.1.15 on 2026-02-25 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_add_assembly_position_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='admin_exempt',
            field=models.BooleanField(default=False, help_text='Exento por Mesa Directiva'),
        ),
        migrations.AddField(
            model_name='unit',
            name='previous_debt',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Adeudo anterior al inicio', max_digits=12),
        ),
    ]
