# Generated by Django

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_add_unit_admin_exempt_previous_debt'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='previous_debt_evidence',
            field=models.TextField(blank=True, default='', help_text='Base64 PDF evidencia del adeudo anterior'),
        ),
    ]
