# Generated by Django

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_add_unit_previous_debt_evidence'),
    ]

    operations = [
        migrations.AddField(
            model_name='unrecognizedincome',
            name='payment_type',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='unrecognizedincome',
            name='notes',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='unrecognizedincome',
            name='bank_reconciled',
            field=models.BooleanField(default=False),
        ),
    ]
