# Generated by Django

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_unrecognized_income_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='additional_payments',
            field=models.JSONField(blank=True, default=list, help_text='Extra payment events: [{field_payments, payment_type, payment_date, notes, bank_reconciled}]'),
        ),
    ]
