# Generated by Django

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_payment_additional_payments'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='bank_reconciled',
            field=models.BooleanField(default=False),
        ),
    ]
