# Generated by Django

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_payment_bank_reconciled'),
    ]

    operations = [
        migrations.AddField(
            model_name='gastoentry',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
    ]
