# Generated by Django

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_gastoentry_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='credit_balance',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Saldo a favor previo al inicio de operaciones', max_digits=12),
        ),
    ]
