# Generated by Django 5.1.15 on 2026-03-04 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_extrafield_show_in_forms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='additional_payments',
            field=models.JSONField(blank=True, default=list, help_text='Extra payment events per unit/period'),
        ),
    ]
