# Generated by Django 5.1.15 on 2026-03-10 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_payment_additional_payments'),
        ('core', '0015_amenity_reservations'),
    ]

    operations = [
    ]
