# Generated by Django 5.1.15 on 2026-03-13 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_email_verification_code'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='amenityreservation',
            new_name='amenity_res_tenant__3e212d_idx',
            old_name='amenity_tenant_date_idx',
        ),
        migrations.RenameIndex(
            model_name='amenityreservation',
            new_name='amenity_res_tenant__522730_idx',
            old_name='amenity_tenant_status_idx',
        ),
        migrations.AlterField(
            model_name='payment',
            name='additional_payments',
            field=models.JSONField(blank=True, default=list, help_text='Extra payment events per unit/period'),
        ),
        migrations.AlterField(
            model_name='tenantuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrador'), ('tesorero', 'Tesorero'), ('contador', 'Contador'), ('auditor', 'Auditor'), ('vecino', 'Vecino / Residente'), ('vigilante', 'Vigilante')], db_index=True, max_length=20),
        ),
    ]
