# Generated by Django 5.1.15 on 2026-03-12 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_condominio_request'),
        ('core', '0017_rename_amenity_tenant_date_idx_amenity_res_tenant__3e212d_idx_and_more'),
    ]

    operations = [
    ]
