# Generated by Django 5.1.15 on 2026-03-13 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_merge_20260311_2326'),
        ('core', '0018_rename_amenity_tenant_date_idx_amenity_res_tenant__3e212d_idx_and_more'),
    ]

    operations = [
    ]
