# Generated by Homly security hardening — riesgo ALTO #3
# Agrega campos FileField junto a los campos Base64 existentes (TextField).
# Los campos Base64 originales se marcan como deprecados pero NO se eliminan todavía
# para mantener compatibilidad retroactiva durante la migración de datos.
# Una vez que todos los registros existan y apunten al nuevo campo,
# ejecutar: python manage.py migrate_base64_to_files
# Y luego crear una migración adicional para remover los campos Base64 obsoletos.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_tenant_hibernation'),
    ]

    operations = [
        # Tenant.logo_file — reemplaza a Tenant.logo (Base64)
        migrations.AddField(
            model_name='tenant',
            name='logo_file',
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to='tenant_logos/',
                help_text='Logo almacenado como archivo. Reemplaza al campo logo (Base64).',
            ),
        ),

        # Unit.previous_debt_evidence_file — reemplaza a Unit.previous_debt_evidence (Base64)
        migrations.AddField(
            model_name='unit',
            name='previous_debt_evidence_file',
            field=models.FileField(
                blank=True,
                null=True,
                upload_to='unit_debt_evidences/',
                help_text='Evidencia de adeudo anterior como archivo. Reemplaza al campo previous_debt_evidence (Base64).',
            ),
        ),

        # Payment.evidence_file — reemplaza a Payment.evidence (Base64)
        migrations.AddField(
            model_name='payment',
            name='evidence_file',
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to='payment_evidences/',
                help_text='Comprobante de pago como archivo. Reemplaza al campo evidence (Base64).',
            ),
        ),

        # GastoEntry.evidence_file — reemplaza a GastoEntry.evidence (Base64)
        migrations.AddField(
            model_name='gastoentry',
            name='evidence_file',
            field=models.FileField(
                blank=True,
                null=True,
                upload_to='gasto_evidences/',
                help_text='Comprobante de gasto como archivo. Reemplaza al campo evidence (Base64).',
            ),
        ),

        # BankStatement.statement_file — reemplaza a BankStatement.file_data (Base64)
        migrations.AddField(
            model_name='bankstatement',
            name='statement_file',
            field=models.FileField(
                blank=True,
                null=True,
                upload_to='bank_statements/',
                help_text='Estado bancario PDF como archivo. Reemplaza al campo file_data (Base64).',
            ),
        ),
    ]
