# Generated by Django 5.1.15 on 2026-09-11 04:56

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0054_unit_services_suspended'),
    ]

    operations = [
        migrations.CreateModel(
            name='RentalCharge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('period', models.CharField(db_index=True, help_text='YYYY-MM', max_length=7)),
                ('description', models.CharField(max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('due_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pendiente', 'Pendiente'), ('parcial', 'Parcial'), ('pagado', 'Pagado'), ('cancelado', 'Cancelado')], db_index=True, default='pendiente', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'rental_charges',
                'ordering': ['-period', 'description'],
            },
        ),
        migrations.CreateModel(
            name='RentalChargeConcept',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('default_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('is_recurring', models.BooleanField(default=True)),
                ('is_rent', models.BooleanField(default=False)),
                ('enabled', models.BooleanField(default=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'rental_charge_concepts',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='RentalContract',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(db_index=True, max_length=40)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('rent_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('deposit_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('payment_day', models.PositiveSmallIntegerField(default=1)),
                ('increment_pct', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('late_fee_pct', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('status', models.CharField(choices=[('borrador', 'Borrador'), ('activo', 'Activo'), ('por_vencer', 'Por vencer'), ('vencido', 'Vencido'), ('renovado', 'Renovado'), ('finalizado', 'Finalizado'), ('cancelado', 'Cancelado')], db_index=True, default='borrador', max_length=20)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'rental_contracts',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='RentalParty',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('inquilino', 'Inquilino'), ('fiador', 'Fiador'), ('propietario', 'Propietario')], db_index=True, default='inquilino', max_length=20)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(blank=True, default='', max_length=150)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('phone', models.CharField(blank=True, default='', max_length=40)),
                ('rfc', models.CharField(blank=True, default='', max_length=20)),
                ('notes', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'rental_parties',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='RentalPayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('payment_date', models.DateField()),
                ('payment_type', models.CharField(choices=[('transfer', 'Transferencia'), ('cash', 'Efectivo'), ('card', 'Tarjeta'), ('check', 'Cheque'), ('other', 'Otro')], default='transfer', max_length=20)),
                ('reference', models.CharField(blank=True, default='', max_length=120)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'rental_payments',
                'ordering': ['-payment_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RentalProperty',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(db_index=True, max_length=40)),
                ('name', models.CharField(max_length=300)),
                ('property_type', models.CharField(choices=[('casa', 'Casa'), ('departamento', 'Departamento'), ('local', 'Local comercial'), ('oficina', 'Oficina'), ('bodega', 'Bodega'), ('terreno', 'Terreno'), ('otro', 'Otro')], default='departamento', max_length=20)),
                ('status', models.CharField(choices=[('disponible', 'Disponible'), ('ocupada', 'Ocupada'), ('reservada', 'Reservada'), ('mantenimiento', 'En mantenimiento'), ('inactiva', 'Inactiva')], db_index=True, default='disponible', max_length=20)),
                ('street', models.CharField(blank=True, default='', max_length=300)),
                ('ext_number', models.CharField(blank=True, default='', max_length=50)),
                ('int_number', models.CharField(blank=True, default='', max_length=50)),
                ('neighborhood', models.CharField(blank=True, default='', max_length=200)),
                ('city', models.CharField(blank=True, default='', max_length=200)),
                ('state', models.CharField(blank=True, default='', max_length=100)),
                ('postal_code', models.CharField(blank=True, default='', max_length=12)),
                ('bedrooms', models.PositiveSmallIntegerField(default=0)),
                ('bathrooms', models.DecimalField(decimal_places=1, default=0, max_digits=4)),
                ('area_m2', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('suggested_rent', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('owner_name', models.CharField(blank=True, default='', max_length=200)),
                ('owner_email', models.EmailField(blank=True, default='', max_length=254)),
                ('owner_phone', models.CharField(blank=True, default='', max_length=40)),
                ('notes', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'rental_properties',
                'ordering': ['code'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='crmcampaigncontact',
            name='unique_campaign_contact',
        ),
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='audit_logs_tenant__6a3dee_idx',
            old_name='audit_tenant_dt_idx',
        ),
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='audit_logs_user_id_6193b2_idx',
            old_name='audit_user_dt_idx',
        ),
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='audit_logs_module_34635f_idx',
            old_name='audit_module_action_idx',
        ),
        migrations.RenameIndex(
            model_name='blogpost',
            new_name='blog_posts_tenant__c5d128_idx',
            old_name='blog_posts_tenant_status_idx',
        ),
        migrations.RenameIndex(
            model_name='blogpost',
            new_name='blog_posts_tenant__36b781_idx',
            old_name='blog_posts_tenant_category_idx',
        ),
        migrations.RenameIndex(
            model_name='notification',
            new_name='notificatio_tenant__391cf9_idx',
            old_name='notif_tenant_user_read_idx',
        ),
        migrations.RenameIndex(
            model_name='paymentvouchersubmission',
            new_name='payment_vou_tenant__00e62e_idx',
            old_name='pvs_tenant_status_idx',
        ),
        migrations.RenameIndex(
            model_name='paymentvouchersubmission',
            new_name='payment_vou_tenant__ddf89c_idx',
            old_name='pvs_tenant_unit_period_idx',
        ),
        migrations.RenameIndex(
            model_name='periodclosurerequest',
            new_name='period_clos_tenant__e06915_idx',
            old_name='pcr_tenant_period_idx',
        ),
        migrations.AddField(
            model_name='tenant',
            name='rental_settings',
            field=models.JSONField(blank=True, default=dict, help_text='Ajustes propios del espacio de rentas (día de cobro, aviso de vencimiento, etc.).'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='workspace_type',
            field=models.CharField(choices=[('condominio', 'Administración de condominios'), ('rentas', 'Gestión de rentas')], db_index=True, default='condominio', help_text='Espacio de trabajo: condominio o inmobiliaria de rentas.', max_length=20),
        ),
        migrations.AlterField(
            model_name='bankstatement',
            name='file_data',
            field=models.TextField(help_text='Base64 encoded PDF (deprecado — usar statement_file)'),
        ),
        migrations.AlterField(
            model_name='crmcampaign',
            name='target_filters',
            field=models.JSONField(blank=True, default=dict, help_text='Audience filter criteria: {status, source, tags, ...}'),
        ),
        migrations.AlterField(
            model_name='gastoentry',
            name='evidence',
            field=models.TextField(blank=True, default='', help_text='Base64 evidence (deprecado — usar evidence_file)'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notif_type',
            field=models.CharField(choices=[('reservation_new', 'Nueva Reserva Solicitada'), ('reservation_approved', 'Reserva Aprobada'), ('reservation_rejected', 'Reserva Rechazada'), ('reservation_cancelled', 'Reserva Cancelada'), ('payment_registered', 'Pago Registrado'), ('payment_updated', 'Pago Actualizado'), ('payment_deleted', 'Cobro Eliminado'), ('period_closed', 'Período Cerrado'), ('period_reopened', 'Período Reabierto'), ('plan_proposal_sent', 'Propuesta de Plan de Pagos Enviada'), ('plan_accepted', 'Plan de Pagos Aceptado'), ('plan_rejected', 'Plan de Pagos Rechazado'), ('plan_cancelled', 'Plan de Pagos Cancelado'), ('general', 'Información General')], db_index=True, default='general', max_length=40),
        ),
        migrations.AlterField(
            model_name='payment',
            name='evidence',
            field=models.TextField(blank=True, default='', help_text='Base64 evidence image (deprecado — usar evidence_file)'),
        ),
        migrations.AlterField(
            model_name='paymentplan',
            name='status',
            field=models.CharField(choices=[('draft', 'Borrador'), ('sent', 'Enviado al residente'), ('accepted', 'Aceptado / Activo'), ('rejected', 'Rechazado'), ('completed', 'Completado'), ('cancelled', 'Cancelado')], db_index=True, default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='subscriptionpayment',
            name='period_label',
            field=models.CharField(blank=True, default='', help_text='Billing period covered, e.g. "Enero 2025" or "2025-01 / 2025-12"', max_length=100),
        ),
        migrations.AlterField(
            model_name='systemrole',
            name='description',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='systemrole',
            name='name',
            field=models.CharField(max_length=120, unique=True),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='logo',
            field=models.TextField(blank=True, default='', help_text='Base64-encoded logo image (deprecado — usar logo_file)'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='module_permissions',
            field=models.JSONField(blank=True, default=dict, help_text='Per-role module visibility. Keys: admin, tesorero, contador, auditor, vigilante, vecino (residente). Values: list of enabled module keys. Empty dict = all defaults enabled.'),
        ),
        migrations.AlterField(
            model_name='tenantuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrador'), ('tesorero', 'Tesorero'), ('contador', 'Contador'), ('auditor', 'Auditor'), ('vecino', 'Residente'), ('vigilante', 'Vigilante')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='tenantuser',
            name='unit',
            field=models.ForeignKey(blank=True, help_text='Required for residente role', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_users', to='core.unit'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='occupancy',
            field=models.CharField(choices=[('propietario', 'Propietario'), ('rentado', 'Rentado'), ('vacío', 'Sin habitar')], default='propietario', max_length=15),
        ),
        migrations.AlterField(
            model_name='unit',
            name='previous_debt_evidence',
            field=models.TextField(blank=True, default='', help_text='Base64 PDF evidencia del adeudo anterior (deprecado — usar previous_debt_evidence_file)'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role_name',
            field=models.CharField(blank=True, default='', help_text='Display label for this user\'s role. Falls back to system_role display or "Super Administrador" if blank.', max_length=120),
        ),
        migrations.AlterUniqueTogether(
            name='crmcampaigncontact',
            unique_together={('campaign', 'contact')},
        ),
        migrations.AddField(
            model_name='rentalcharge',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rental_charges', to='core.tenant'),
        ),
        migrations.AddField(
            model_name='rentalchargeconcept',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rental_concepts', to='core.tenant'),
        ),
        migrations.AddField(
            model_name='rentalcharge',
            name='concept',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='charges', to='core.rentalchargeconcept'),
        ),
        migrations.AddField(
            model_name='rentalcontract',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rental_contracts', to='core.tenant'),
        ),
        migrations.AddField(
            model_name='rentalcharge',
            name='contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charges', to='core.rentalcontract'),
        ),
        migrations.AddField(
            model_name='rentalparty',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rental_parties', to='core.tenant'),
        ),
        migrations.AddField(
            model_name='rentalcontract',
            name='guarantor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guaranteed_contracts', to='core.rentalparty'),
        ),
        migrations.AddField(
            model_name='rentalcontract',
            name='tenant_party',
            field=models.ForeignKey(help_text='Inquilino titular del contrato.', on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='core.rentalparty'),
        ),
        migrations.AddField(
            model_name='rentalpayment',
            name='charge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='core.rentalcharge'),
        ),
        migrations.AddField(
            model_name='rentalpayment',
            name='contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='core.rentalcontract'),
        ),
        migrations.AddField(
            model_name='rentalpayment',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rental_payments', to='core.tenant'),
        ),
        migrations.AddField(
            model_name='rentalproperty',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rental_properties', to='core.tenant'),
        ),
        migrations.AddField(
            model_name='rentalcontract',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='core.rentalproperty'),
        ),
        migrations.AlterUniqueTogether(
            name='rentalchargeconcept',
            unique_together={('tenant', 'name')},
        ),
        migrations.AddIndex(
            model_name='rentalcharge',
            index=models.Index(fields=['tenant', 'period', 'status'], name='rental_char_tenant__064e3e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='rentalproperty',
            unique_together={('tenant', 'code')},
        ),
        migrations.AddIndex(
            model_name='rentalcontract',
            index=models.Index(fields=['tenant', 'status'], name='rental_cont_tenant__4ca723_idx'),
        ),
        migrations.AddIndex(
            model_name='rentalcontract',
            index=models.Index(fields=['tenant', 'end_date'], name='rental_cont_tenant__1f5c0f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='rentalcontract',
            unique_together={('tenant', 'code')},
        ),
    ]
