# Generated by Homly for Airbnb rentas integration

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0056_subscriptionplan_workspace_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentalproperty',
            name='source',
            field=models.CharField(db_index=True, default='homly', help_text='homly | airbnb', max_length=20),
        ),
        migrations.AddField(
            model_name='rentalproperty',
            name='airbnb_listing_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=40),
        ),
        migrations.CreateModel(
            name='AirbnbConnection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(help_text='Ej. Cuenta personal, Cuenta de la inmobiliaria', max_length=160)),
                ('host_email', models.EmailField(blank=True, default='', help_text='Correo del anfitrión en Airbnb (identificador, no contraseña)', max_length=254)),
                ('mode', models.CharField(choices=[('ical', 'Calendario iCal (oficial del anfitrión)'), ('oauth', 'API partner (cuando Homly esté aprobado)')], default='ical', max_length=12)),
                ('notes', models.TextField(blank=True, default='')),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='airbnb_connections', to='core.tenant')),
            ],
            options={
                'db_table': 'airbnb_connections',
                'ordering': ['label'],
            },
        ),
        migrations.CreateModel(
            name='AirbnbListing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('airbnb_listing_id', models.CharField(db_index=True, max_length=40)),
                ('listing_url', models.URLField(blank=True, default='', max_length=500)),
                ('ical_url', models.URLField(blank=True, default='', help_text='URL de exportación de calendario que Airbnb da al anfitrión', max_length=800)),
                ('listing_name', models.CharField(max_length=300)),
                ('sync_enabled', models.BooleanField(default=True)),
                ('occupied_now', models.BooleanField(default=False)),
                ('ical_events', models.JSONField(blank=True, default=list)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('last_sync_error', models.CharField(blank=True, default='', max_length=400)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to='core.airbnbconnection')),
                ('property', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='airbnb_listing', to='core.rentalproperty')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='airbnb_listings', to='core.tenant')),
            ],
            options={
                'db_table': 'airbnb_listings',
                'ordering': ['listing_name'],
                'unique_together': {('tenant', 'airbnb_listing_id')},
            },
        ),
    ]
