# Generated by Homly for rentas CRM (leads → contract)

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models
import django.core.validators


def add_crm_module_to_rentas_plans(apps, schema_editor):
    SubscriptionPlan = apps.get_model('core', 'SubscriptionPlan')
    for plan in SubscriptionPlan.objects.filter(workspace_type='rentas'):
        mods = list(plan.allowed_modules or [])
        if mods and 'rentas_crm' not in mods:
            mods.append('rentas_crm')
            plan.allowed_modules = mods
            plan.save(update_fields=['allowed_modules'])


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0057_airbnb_connections_listings'),
    ]

    operations = [
        migrations.CreateModel(
            name='RentalLead',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(blank=True, default='', max_length=150)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('phone', models.CharField(blank=True, default='', max_length=40)),
                ('source', models.CharField(choices=[('web', 'Sitio web'), ('whatsapp', 'WhatsApp'), ('telefono', 'Teléfono'), ('visita', 'Visita al inmueble'), ('airbnb', 'Airbnb'), ('referido', 'Referido'), ('otro', 'Otro')], db_index=True, default='otro', max_length=20)),
                ('stage', models.CharField(choices=[('nuevo', 'Nuevo'), ('contactado', 'Contactado'), ('visita', 'Visita'), ('propuesta', 'Propuesta'), ('negociacion', 'Negociación'), ('ganado', 'Ganado'), ('perdido', 'Perdido')], db_index=True, default='nuevo', max_length=20)),
                ('interested_rent', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('expected_start', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('lost_reason', models.CharField(blank=True, default='', max_length=300)),
                ('converted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rental_leads_assigned', to=settings.AUTH_USER_MODEL)),
                ('contract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_leads', to='core.rentalcontract')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rental_leads_created', to=settings.AUTH_USER_MODEL)),
                ('party', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='core.rentalparty')),
                ('rental_property', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='core.rentalproperty')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rental_leads', to='core.tenant')),
            ],
            options={
                'db_table': 'rental_leads',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RentalLeadActivity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('note', 'Nota'), ('call', 'Llamada'), ('whatsapp', 'WhatsApp'), ('email', 'Correo'), ('visit', 'Visita'), ('system', 'Sistema')], default='note', max_length=16)),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rental_lead_activities_created', to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='core.rentallead')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rental_lead_activities', to='core.tenant')),
            ],
            options={
                'db_table': 'rental_lead_activities',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='rentallead',
            index=models.Index(fields=['tenant', 'stage'], name='rental_lead_tenant__stage_idx'),
        ),
        migrations.AddIndex(
            model_name='rentallead',
            index=models.Index(fields=['tenant', 'rental_property'], name='rental_lead_tenant__prop_idx'),
        ),
        migrations.RunPython(add_crm_module_to_rentas_plans, migrations.RunPython.noop),
    ]
