# Generated by Homly — rentas_rentroll module on existing plans

from django.db import migrations


def add_rentroll_module(apps, schema_editor):
    SubscriptionPlan = apps.get_model('core', 'SubscriptionPlan')
    for plan in SubscriptionPlan.objects.filter(workspace_type='rentas'):
        mods = list(plan.allowed_modules or [])
        if mods and 'rentas_rentroll' not in mods:
            mods.append('rentas_rentroll')
            plan.allowed_modules = mods
            plan.save(update_fields=['allowed_modules'])


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0058_rental_leads_crm'),
    ]

    operations = [
        migrations.RunPython(add_rentroll_module, migrations.RunPython.noop),
    ]
