# Generated by Django 5.1.15 on 2026-09-11 06:35

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


def add_planeacion_module(apps, schema_editor):
    SubscriptionPlan = apps.get_model('core', 'SubscriptionPlan')
    for plan in SubscriptionPlan.objects.filter(workspace_type='condominio'):
        mods = list(plan.allowed_modules or [])
        if mods and 'planeacion' not in mods:
            mods.append('planeacion')
            plan.allowed_modules = mods
            plan.save(update_fields=['allowed_modules'])


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0059_rentas_rentroll_module'),
    ]

    operations = [
        migrations.CreateModel(
            name='CondoBudget',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('year', models.PositiveSmallIntegerField(db_index=True)),
                ('name', models.CharField(blank=True, default='', max_length=200)),
                ('notes', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('borrador', 'Borrador'), ('aprobado', 'Aprobado'), ('archivado', 'Archivado')], db_index=True, default='borrador', max_length=16)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'condo_budgets',
                'ordering': ['-year', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CondoBudgetLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('ingreso', 'Ingreso'), ('gasto', 'Gasto')], db_index=True, max_length=12)),
                ('concept_key', models.CharField(db_index=True, help_text='maintenance | caja_chica | extra_field UUID | custom', max_length=80)),
                ('name', models.CharField(max_length=200)),
                ('monthly_amounts', models.JSONField(blank=True, default=dict)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'condo_budget_lines',
                'ordering': ['kind', 'sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CondoProject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=240)),
                ('description', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('idea', 'Idea'), ('aprobado', 'Aprobado'), ('en_curso', 'En curso'), ('pausado', 'Pausado'), ('concluido', 'Concluido'), ('cancelado', 'Cancelado')], db_index=True, default='idea', max_length=16)),
                ('priority', models.CharField(choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta'), ('urgente', 'Urgente')], default='media', max_length=12)),
                ('budget_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14, validators=[django.core.validators.MinValueValidator(0)])),
                ('start_period', models.CharField(blank=True, default='', help_text='YYYY-MM', max_length=7)),
                ('end_period', models.CharField(blank=True, default='', help_text='YYYY-MM', max_length=7)),
                ('responsible_name', models.CharField(blank=True, default='', max_length=200)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'condo_projects',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CondoProjectCost',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('period', models.CharField(db_index=True, max_length=7)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('description', models.CharField(blank=True, default='', max_length=400)),
                ('cost_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'condo_project_costs',
                'ordering': ['-period', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='condobudget',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='condo_budgets_approved', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='condobudget',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='condo_budgets_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='condobudget',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='condo_budgets', to='core.tenant'),
        ),
        migrations.AddField(
            model_name='condobudgetline',
            name='budget',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='core.condobudget'),
        ),
        migrations.AddField(
            model_name='condobudgetline',
            name='extra_field',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='budget_lines', to='core.extrafield'),
        ),
        migrations.AddField(
            model_name='condoproject',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='condo_projects_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='condoproject',
            name='extra_field',
            field=models.ForeignKey(blank=True, help_text='Categoría de gastos con la que se compara el avance.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='condo_projects', to='core.extrafield'),
        ),
        migrations.AddField(
            model_name='condoproject',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='condo_projects', to='core.tenant'),
        ),
        migrations.AddField(
            model_name='condoprojectcost',
            name='extra_field',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_costs', to='core.extrafield'),
        ),
        migrations.AddField(
            model_name='condoprojectcost',
            name='gasto_entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_costs', to='core.gastoentry'),
        ),
        migrations.AddField(
            model_name='condoprojectcost',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='costs', to='core.condoproject'),
        ),
        migrations.AddIndex(
            model_name='condobudget',
            index=models.Index(fields=['tenant', 'year'], name='condo_budge_tenant__68725f_idx'),
        ),
        migrations.AddIndex(
            model_name='condobudget',
            index=models.Index(fields=['tenant', 'status'], name='condo_budge_tenant__d6284c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='condobudget',
            unique_together={('tenant', 'year')},
        ),
        migrations.AddIndex(
            model_name='condoproject',
            index=models.Index(fields=['tenant', 'status'], name='condo_proje_tenant__ed922a_idx'),
        ),
        migrations.AddIndex(
            model_name='condoprojectcost',
            index=models.Index(fields=['project', 'period'], name='condo_proje_project_de6790_idx'),
        ),
        migrations.RunPython(add_planeacion_module, migrations.RunPython.noop),
    ]
