# Generated by Django 5.1.15 on 2026-09-11 07:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0061_rentas_notification_emails'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='condobudget',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='condobudget',
            name='approval_steps',
            field=models.JSONField(blank=True, default=list, help_text='Pasos del flujo de aprobación en curso.'),
        ),
        migrations.AddField(
            model_name='condobudget',
            name='cashflow_rules',
            field=models.JSONField(blank=True, default=list, help_text='Descuentos/incentivos de cobranza: [{id,name,pct,takeup_pct,apply_to}]'),
        ),
        migrations.AddField(
            model_name='condobudget',
            name='seed_fee',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Cuota de mantenimiento usada para armar el sugerido.', max_digits=14, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='condobudget',
            name='seed_units',
            field=models.PositiveIntegerField(default=0, help_text='Unidades usadas para el sugerido (no puede superar las unidades activas del tenant).'),
        ),
        migrations.AddField(
            model_name='condoproject',
            name='approval_steps',
            field=models.JSONField(blank=True, default=list, help_text='Pasos del flujo de aprobación en curso.'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='planning_flow',
            field=models.JSONField(blank=True, default=dict, help_text='Flujo de aprobación de presupuesto y proyectos: enabled y pasos ordenados.'),
        ),
        migrations.AlterField(
            model_name='condobudget',
            name='status',
            field=models.CharField(choices=[('borrador', 'Borrador'), ('en_aprobacion', 'En aprobación'), ('aprobado', 'Aprobado'), ('archivado', 'Archivado')], db_index=True, default='borrador', max_length=16),
        ),
        migrations.AlterField(
            model_name='condoproject',
            name='status',
            field=models.CharField(choices=[('idea', 'Idea'), ('en_aprobacion', 'En aprobación'), ('aprobado', 'Aprobado'), ('en_curso', 'En curso'), ('pausado', 'Pausado'), ('concluido', 'Concluido'), ('cancelado', 'Cancelado')], db_index=True, default='idea', max_length=16),
        ),
    ]
