# Generated by Django 5.1.15 on 2026-09-11 08:26

import core.models
import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0063_condo_budget_status_guardado'),
    ]

    operations = [
        migrations.CreateModel(
            name='CondoProjectFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('cotizacion', 'Cotización'), ('plano', 'Plano'), ('contrato', 'Contrato'), ('foto', 'Foto'), ('documento', 'Documento'), ('otro', 'Otro')], default='documento', max_length=16)),
                ('original_name', models.CharField(blank=True, default='', max_length=240)),
                ('notes', models.CharField(blank=True, default='', max_length=400)),
                ('file', models.FileField(upload_to=core.models.condo_project_file_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'condo_project_files',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CondoProjectQuote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('supplier_name', models.CharField(max_length=240)),
                ('supplier_rfc', models.CharField(blank=True, default='', max_length=20)),
                ('supplier_contact', models.CharField(blank=True, default='', max_length=200)),
                ('supplier_phone', models.CharField(blank=True, default='', max_length=40)),
                ('supplier_email', models.CharField(blank=True, default='', max_length=200)),
                ('supplier_notes', models.TextField(blank=True, default='')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(0)])),
                ('validity_date', models.DateField(blank=True, null=True)),
                ('delivery_days', models.PositiveIntegerField(blank=True, null=True)),
                ('warranty_months', models.PositiveIntegerField(blank=True, null=True)),
                ('scope', models.TextField(blank=True, default='')),
                ('is_winner', models.BooleanField(default=False)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'condo_project_quotes',
                'ordering': ['sort_order', 'created_at'],
            },
        ),
        migrations.AddField(
            model_name='condobudgetline',
            name='project',
            field=models.ForeignKey(blank=True, help_text='Partida generada al incluir un proyecto en este presupuesto.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='budget_lines', to='core.condoproject'),
        ),
        migrations.AddField(
            model_name='condoproject',
            name='budget',
            field=models.ForeignKey(blank=True, help_text='Presupuesto anual donde está incluida la partida del proyecto.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_projects', to='core.condobudget'),
        ),
        migrations.AddField(
            model_name='condoproject',
            name='contest_status',
            field=models.CharField(choices=[('sin_concurso', 'Sin concurso'), ('en_concurso', 'En concurso'), ('adjudicado', 'Adjudicado')], db_index=True, default='sin_concurso', max_length=16),
        ),
        migrations.AddField(
            model_name='condoproject',
            name='funding_condo_pct',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='condoproject',
            name='funding_mode',
            field=models.CharField(choices=[('condominio', 'Recursos del condominio'), ('residentes', 'Aportes extraordinarios de residentes'), ('compartido', 'Compartido')], default='condominio', max_length=16),
        ),
        migrations.AddField(
            model_name='condoproject',
            name='funding_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='condoproject',
            name='funding_residents_pct',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='condoproject',
            name='funding_units',
            field=models.PositiveIntegerField(default=0, help_text='Unidades que aportan la parte de residentes (0 = usar las activas del tenant).'),
        ),
        migrations.AddField(
            model_name='condoprojectfile',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='core.condoproject'),
        ),
        migrations.AddField(
            model_name='condoprojectfile',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='condo_project_files_uploaded', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='condoprojectquote',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to='core.condoproject'),
        ),
        migrations.AddField(
            model_name='condoprojectfile',
            name='quote',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='core.condoprojectquote'),
        ),
        migrations.AddField(
            model_name='condoproject',
            name='winner_quote',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won_projects', to='core.condoprojectquote'),
        ),
    ]
