# Generated by Django 5.1.15 on 2026-09-12 05:20

import core.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


def add_asambleas_module(apps, schema_editor):
    SubscriptionPlan = apps.get_model('core', 'SubscriptionPlan')
    for plan in SubscriptionPlan.objects.filter(workspace_type='condominio'):
        mods = list(plan.allowed_modules or [])
        if mods and 'asambleas' not in mods:
            mods.append('asambleas')
            plan.allowed_modules = mods
            plan.save(update_fields=['allowed_modules'])


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0064_condo_project_quotes_files_funding'),
    ]

    operations = [
        migrations.CreateModel(
            name='CondoAssembly',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=240)),
                ('kind', models.CharField(choices=[('ordinaria', 'Ordinaria'), ('extraordinaria', 'Extraordinaria')], db_index=True, default='ordinaria', max_length=16)),
                ('year', models.PositiveSmallIntegerField(db_index=True)),
                ('status', models.CharField(choices=[('borrador', 'Borrador'), ('convocada', 'Convocada'), ('en_curso', 'En curso'), ('cerrada', 'Cerrada'), ('cancelada', 'Cancelada')], db_index=True, default='borrador', max_length=16)),
                ('location', models.CharField(blank=True, default='', max_length=300)),
                ('first_call_at', models.DateTimeField(blank=True, null=True)),
                ('second_call_at', models.DateTimeField(blank=True, null=True)),
                ('call_number', models.PositiveSmallIntegerField(default=1)),
                ('notice_issued_at', models.DateTimeField(blank=True, null=True)),
                ('notice_days', models.PositiveSmallIntegerField(default=10)),
                ('delivery_methods', models.JSONField(blank=True, default=list)),
                ('issued_by_name', models.CharField(blank=True, default='', max_length=200)),
                ('president_name', models.CharField(blank=True, default='', max_length=200)),
                ('secretary_name', models.CharField(blank=True, default='', max_length=200)),
                ('legal_snapshot', models.JSONField(blank=True, default=dict)),
                ('minute_body', models.TextField(blank=True, default='')),
                ('minute_status', models.CharField(choices=[('borrador', 'Borrador'), ('firmada', 'Firmada'), ('protocolizada', 'Protocolizada')], default='borrador', max_length=16)),
                ('minute_signed_at', models.DateTimeField(blank=True, null=True)),
                ('protocolized', models.BooleanField(default=False)),
                ('notary_name', models.CharField(blank=True, default='', max_length=200)),
                ('notary_folio', models.CharField(blank=True, default='', max_length=80)),
                ('installed_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'condo_assemblies',
                'ordering': ['-first_call_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CondoAssemblyAgendaItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('title', models.CharField(max_length=240)),
                ('description', models.TextField(blank=True, default='')),
                ('vote_type', models.CharField(choices=[('informativo', 'Informativo'), ('simple', 'Mayoría simple'), ('calificada', 'Mayoría calificada'), ('unanimidad', 'Unanimidad')], default='simple', max_length=16)),
                ('result', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado'), ('diferido', 'Diferido')], default='pendiente', max_length=16)),
                ('votes_for', models.PositiveIntegerField(default=0)),
                ('votes_against', models.PositiveIntegerField(default=0)),
                ('votes_abstain', models.PositiveIntegerField(default=0)),
                ('notes', models.CharField(blank=True, default='', max_length=400)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'condo_assembly_agenda',
                'ordering': ['sort_order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='CondoAssemblyAttendee',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('attendee_name', models.CharField(blank=True, default='', max_length=240)),
                ('capacity', models.CharField(choices=[('propietario', 'Propietario'), ('representante', 'Representante / carta poder'), ('invitado', 'Invitado')], default='propietario', max_length=16)),
                ('proxy_name', models.CharField(blank=True, default='', max_length=200)),
                ('present', models.BooleanField(default=False)),
                ('vote_weight', models.DecimalField(decimal_places=4, default=1, max_digits=8)),
                ('signed_in_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'condo_assembly_attendees',
                'ordering': ['unit__unit_id_code', 'attendee_name'],
            },
        ),
        migrations.CreateModel(
            name='CondoAssemblyFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('convocatoria', 'Convocatoria'), ('poder', 'Carta poder'), ('lista', 'Lista de asistencia'), ('minuta', 'Minuta / acta'), ('evidencia', 'Evidencia de notificación'), ('otro', 'Otro')], default='otro', max_length=16)),
                ('original_name', models.CharField(blank=True, default='', max_length=240)),
                ('notes', models.CharField(blank=True, default='', max_length=400)),
                ('file', models.FileField(upload_to=core.models.condo_assembly_file_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'condo_assembly_files',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RunPython(add_asambleas_module, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='notification',
            name='notif_type',
            field=models.CharField(choices=[('reservation_new', 'Nueva Reserva Solicitada'), ('reservation_approved', 'Reserva Aprobada'), ('reservation_rejected', 'Reserva Rechazada'), ('reservation_cancelled', 'Reserva Cancelada'), ('payment_registered', 'Pago Registrado'), ('payment_updated', 'Pago Actualizado'), ('payment_deleted', 'Cobro Eliminado'), ('period_closed', 'Período Cerrado'), ('period_reopened', 'Período Reabierto'), ('plan_proposal_sent', 'Propuesta de Plan de Pagos Enviada'), ('plan_accepted', 'Plan de Pagos Aceptado'), ('plan_rejected', 'Plan de Pagos Rechazado'), ('plan_cancelled', 'Plan de Pagos Cancelado'), ('rental_property_created', 'Propiedad registrada'), ('rental_property_status', 'Estado de propiedad'), ('rental_contract_created', 'Contrato creado'), ('rental_contract_activated', 'Contrato activado'), ('rental_contract_finished', 'Contrato cerrado'), ('rental_contract_expiring', 'Contrato por vencer'), ('rental_contract_expired', 'Contrato vencido'), ('rental_charge_generated', 'Cargos del período'), ('rental_payment_registered', 'Pago de renta'), ('rental_payment_deleted', 'Pago de renta eliminado'), ('rental_lead_created', 'Nuevo lead'), ('rental_lead_moved', 'Lead actualizado'), ('rental_lead_converted', 'Lead convertido'), ('rental_lead_lost', 'Lead perdido'), ('rental_airbnb_imported', 'Airbnb importado'), ('rental_airbnb_synced', 'Airbnb sincronizado'), ('rental_airbnb_error', 'Error de Airbnb'), ('assembly_notice', 'Convocatoria de asamblea'), ('assembly_started', 'Asamblea en curso'), ('assembly_minute', 'Minuta de asamblea'), ('general', 'Información General')], db_index=True, default='general', max_length=40),
        ),
        migrations.AddField(
            model_name='condoassembly',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='condo_assemblies_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='condoassembly',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='condo_assemblies', to='core.tenant'),
        ),
        migrations.AddField(
            model_name='condoassemblyagendaitem',
            name='assembly',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agenda', to='core.condoassembly'),
        ),
        migrations.AddField(
            model_name='condoassemblyattendee',
            name='assembly',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendees', to='core.condoassembly'),
        ),
        migrations.AddField(
            model_name='condoassemblyattendee',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assembly_attendances', to='core.unit'),
        ),
        migrations.AddField(
            model_name='condoassemblyfile',
            name='assembly',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='core.condoassembly'),
        ),
        migrations.AddField(
            model_name='condoassemblyfile',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='condo_assembly_files_uploaded', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='condoassembly',
            index=models.Index(fields=['tenant', 'status'], name='condo_assem_tenant__04fe64_idx'),
        ),
        migrations.AddIndex(
            model_name='condoassembly',
            index=models.Index(fields=['tenant', 'year'], name='condo_assem_tenant__56b034_idx'),
        ),
        migrations.AddIndex(
            model_name='condoassemblyattendee',
            index=models.Index(fields=['assembly', 'present'], name='condo_assem_assembl_fe87ca_idx'),
        ),
    ]
