# Generated by Django 5.1.15 on 2026-09-12 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0065_condo_assemblies_module'),
    ]

    operations = [
        migrations.AddField(
            model_name='condoassemblyagendaitem',
            name='source_kind',
            field=models.CharField(
                choices=[
                    ('manual', 'Manual'),
                    ('presupuesto', 'Presupuesto (Planeación)'),
                    ('proyecto', 'Proyecto (Planeación)'),
                    ('cierre', 'Cierre de período'),
                    ('cuota', 'Cuota / cargo extra'),
                    ('organizacion', 'Comité / cargo'),
                ],
                default='manual',
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name='condoassemblyagendaitem',
            name='source_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='condoassemblyagendaitem',
            name='source_label',
            field=models.CharField(blank=True, default='', max_length=240),
        ),
        migrations.AddField(
            model_name='condoassemblyagendaitem',
            name='source_meta',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='condoassemblyagendaitem',
            name='apply_on_approve',
            field=models.BooleanField(
                default=False,
                help_text='Si el punto se aprueba en asamblea, actualizar el módulo origen (presupuesto/proyecto).',
            ),
        ),
        migrations.AddField(
            model_name='condoassemblyagendaitem',
            name='applied_status',
            field=models.CharField(
                choices=[
                    ('pendiente', 'Pendiente'),
                    ('aplicado', 'Aplicado en el módulo'),
                    ('omitido', 'Solo constancia'),
                    ('error', 'No se pudo aplicar'),
                ],
                default='pendiente',
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name='condoassemblyagendaitem',
            name='applied_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='condoassemblyagendaitem',
            name='applied_notes',
            field=models.CharField(blank=True, default='', max_length=400),
        ),
    ]
